# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergei/Projects/ROOTTools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergei/Projects/ROOTTools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/ROOTTools/CMakeFiles /home/sergei/Projects/ROOTTools//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/ROOTTools/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/ROOTTools/CMakeFiles /home/sergei/Projects/ROOTTools//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/ROOTTools/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TCanvasTools

# Build rule for target.
TCanvasTools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TCanvasTools
.PHONY : TCanvasTools

# fast build rule for target.
TCanvasTools/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TCanvasTools.dir/build.make CMakeFiles/TCanvasTools.dir/build
.PHONY : TCanvasTools/fast

#=============================================================================
# Target rules for targets named TF1Tools

# Build rule for target.
TF1Tools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TF1Tools
.PHONY : TF1Tools

# fast build rule for target.
TF1Tools/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TF1Tools.dir/build.make CMakeFiles/TF1Tools.dir/build
.PHONY : TF1Tools/fast

#=============================================================================
# Target rules for targets named ThrObj

# Build rule for target.
ThrObj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThrObj
.PHONY : ThrObj

# fast build rule for target.
ThrObj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThrObj.dir/build.make CMakeFiles/ThrObj.dir/build
.PHONY : ThrObj/fast

#=============================================================================
# Target rules for targets named GUIDistrCutter2D

# Build rule for target.
GUIDistrCutter2D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GUIDistrCutter2D
.PHONY : GUIDistrCutter2D

# fast build rule for target.
GUIDistrCutter2D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIDistrCutter2D.dir/build.make CMakeFiles/GUIDistrCutter2D.dir/build
.PHONY : GUIDistrCutter2D/fast

src/GUIDistrCutter2D.o: src/GUIDistrCutter2D.cpp.o
.PHONY : src/GUIDistrCutter2D.o

# target to build an object file
src/GUIDistrCutter2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIDistrCutter2D.dir/build.make CMakeFiles/GUIDistrCutter2D.dir/src/GUIDistrCutter2D.cpp.o
.PHONY : src/GUIDistrCutter2D.cpp.o

src/GUIDistrCutter2D.i: src/GUIDistrCutter2D.cpp.i
.PHONY : src/GUIDistrCutter2D.i

# target to preprocess a source file
src/GUIDistrCutter2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIDistrCutter2D.dir/build.make CMakeFiles/GUIDistrCutter2D.dir/src/GUIDistrCutter2D.cpp.i
.PHONY : src/GUIDistrCutter2D.cpp.i

src/GUIDistrCutter2D.s: src/GUIDistrCutter2D.cpp.s
.PHONY : src/GUIDistrCutter2D.s

# target to generate assembly for a file
src/GUIDistrCutter2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIDistrCutter2D.dir/build.make CMakeFiles/GUIDistrCutter2D.dir/src/GUIDistrCutter2D.cpp.s
.PHONY : src/GUIDistrCutter2D.cpp.s

src/TCanvasTools.o: src/TCanvasTools.cpp.o
.PHONY : src/TCanvasTools.o

# target to build an object file
src/TCanvasTools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TCanvasTools.dir/build.make CMakeFiles/TCanvasTools.dir/src/TCanvasTools.cpp.o
.PHONY : src/TCanvasTools.cpp.o

src/TCanvasTools.i: src/TCanvasTools.cpp.i
.PHONY : src/TCanvasTools.i

# target to preprocess a source file
src/TCanvasTools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TCanvasTools.dir/build.make CMakeFiles/TCanvasTools.dir/src/TCanvasTools.cpp.i
.PHONY : src/TCanvasTools.cpp.i

src/TCanvasTools.s: src/TCanvasTools.cpp.s
.PHONY : src/TCanvasTools.s

# target to generate assembly for a file
src/TCanvasTools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TCanvasTools.dir/build.make CMakeFiles/TCanvasTools.dir/src/TCanvasTools.cpp.s
.PHONY : src/TCanvasTools.cpp.s

src/TF1Tools.o: src/TF1Tools.cpp.o
.PHONY : src/TF1Tools.o

# target to build an object file
src/TF1Tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TF1Tools.dir/build.make CMakeFiles/TF1Tools.dir/src/TF1Tools.cpp.o
.PHONY : src/TF1Tools.cpp.o

src/TF1Tools.i: src/TF1Tools.cpp.i
.PHONY : src/TF1Tools.i

# target to preprocess a source file
src/TF1Tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TF1Tools.dir/build.make CMakeFiles/TF1Tools.dir/src/TF1Tools.cpp.i
.PHONY : src/TF1Tools.cpp.i

src/TF1Tools.s: src/TF1Tools.cpp.s
.PHONY : src/TF1Tools.s

# target to generate assembly for a file
src/TF1Tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TF1Tools.dir/build.make CMakeFiles/TF1Tools.dir/src/TF1Tools.cpp.s
.PHONY : src/TF1Tools.cpp.s

src/ThrObj.o: src/ThrObj.cpp.o
.PHONY : src/ThrObj.o

# target to build an object file
src/ThrObj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThrObj.dir/build.make CMakeFiles/ThrObj.dir/src/ThrObj.cpp.o
.PHONY : src/ThrObj.cpp.o

src/ThrObj.i: src/ThrObj.cpp.i
.PHONY : src/ThrObj.i

# target to preprocess a source file
src/ThrObj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThrObj.dir/build.make CMakeFiles/ThrObj.dir/src/ThrObj.cpp.i
.PHONY : src/ThrObj.cpp.i

src/ThrObj.s: src/ThrObj.cpp.s
.PHONY : src/ThrObj.s

# target to generate assembly for a file
src/ThrObj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThrObj.dir/build.make CMakeFiles/ThrObj.dir/src/ThrObj.cpp.s
.PHONY : src/ThrObj.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GUIDistrCutter2D"
	@echo "... TCanvasTools"
	@echo "... TF1Tools"
	@echo "... ThrObj"
	@echo "... src/GUIDistrCutter2D.o"
	@echo "... src/GUIDistrCutter2D.i"
	@echo "... src/GUIDistrCutter2D.s"
	@echo "... src/TCanvasTools.o"
	@echo "... src/TCanvasTools.i"
	@echo "... src/TCanvasTools.s"
	@echo "... src/TF1Tools.o"
	@echo "... src/TF1Tools.i"
	@echo "... src/TF1Tools.s"
	@echo "... src/ThrObj.o"
	@echo "... src/ThrObj.i"
	@echo "... src/ThrObj.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

